//省
var ProJson = [
    { "ProID": 1, "ProName": "北京", "ProSort": 1, "ProRemark": "直辖市" },
    { "ProID": 2, "ProName": "天津", "ProSort": 2, "ProRemark": "直辖市" },
    { "ProID": 9, "ProName": "上海", "ProSort": 3, "ProRemark": "直辖市" },
    { "ProID": 27, "ProName": "重庆", "ProSort": 4, "ProRemark": "直辖市" },
    { "ProID": 3, "ProName": "河北", "ProSort": 5, "ProRemark": "省份" },
    { "ProID": 4, "ProName": "山西", "ProSort": 6, "ProRemark": "省份" },
    { "ProID": 5, "ProName": "内蒙古", "ProSort": 32, "ProRemark": "自治区" },
    { "ProID": 6, "ProName": "辽宁", "ProSort": 8, "ProRemark": "省份" },
    { "ProID": 7, "ProName": "吉林", "ProSort": 9, "ProRemark": "省份" },
    { "ProID": 8, "ProName": "黑龙江", "ProSort": 10, "ProRemark": "省份" },
    { "ProID": 10, "ProName": "江苏", "ProSort": 11, "ProRemark": "省份" },
    { "ProID": 11, "ProName": "浙江", "ProSort": 12, "ProRemark": "省份" },
    { "ProID": 12, "ProName": "安徽", "ProSort": 13, "ProRemark": "省份" },
    { "ProID": 13, "ProName": "福建", "ProSort": 14, "ProRemark": "省份" },
    { "ProID": 14, "ProName": "江西", "ProSort": 15, "ProRemark": "省份" },
    { "ProID": 15, "ProName": "山东", "ProSort": 16, "ProRemark": "省份" },
    { "ProID": 16, "ProName": "河南", "ProSort": 17, "ProRemark": "省份" },
    { "ProID": 17, "ProName": "湖北", "ProSort": 18, "ProRemark": "省份" },
    { "ProID": 18, "ProName": "湖南", "ProSort": 19, "ProRemark": "省份" },
    { "ProID": 19, "ProName": "广东", "ProSort": 20, "ProRemark": "省份" },
    { "ProID": 20, "ProName": "海南", "ProSort": 24, "ProRemark": "省份" },
    { "ProID": 21, "ProName": "广西", "ProSort": 28, "ProRemark": "自治区" },
    { "ProID": 22, "ProName": "甘肃", "ProSort": 21, "ProRemark": "省份" },
    { "ProID": 23, "ProName": "陕西", "ProSort": 27, "ProRemark": "省份" },
    { "ProID": 24, "ProName": "新疆", "ProSort": 31, "ProRemark": "自治区" },
    { "ProID": 25, "ProName": "青海", "ProSort": 26, "ProRemark": "省份" },
    { "ProID": 26, "ProName": "宁夏", "ProSort": 30, "ProRemark": "自治区" },
    { "ProID": 28, "ProName": "四川", "ProSort": 22, "ProRemark": "省份" },
    { "ProID": 29, "ProName": "贵州", "ProSort": 23, "ProRemark": "省份" },
    { "ProID": 30, "ProName": "云南", "ProSort": 25, "ProRemark": "省份" },
    { "ProID": 31, "ProName": "西藏", "ProSort": 29, "ProRemark": "自治区" },
    { "ProID": 32, "ProName": "台湾", "ProSort": 7, "ProRemark": "省份" },
    { "ProID": 33, "ProName": "澳门", "ProSort": 33, "ProRemark": "特别行政区" },
    { "ProID": 34, "ProName": "香港", "ProSort": 34, "ProRemark": "特别行政区"}
]